### ISSUE TITLE
CentOS 9: authentication error on gateway prelogin interface

### ISSUE THREAD

**Issue by ng0177** [yuezk/GlobalProtect-openconnect#143]
This error only occurs under `CentOS 9` using `OBS: globalprotect-openconnect`. Other OSs such as `Arch` work seamless.

**Comment by jaykay0079** [comment]
I have similar issue on Ubuntu 22.04

**Comment by impsik** [comment]
Temporary solution:
https://github.com/yuezk/GlobalProtect-openconnect/issues/142#issuecomment-1106489685

**Comment by LauroSilveira** [comment]
I have the same issue on Ubuntu 22.04.
Is there any date to fix it?

**Comment by yuezk** [comment]
@LauroSilveira 
The reason is that the TLS configuration on GlobalProtect VPN gateway server isn't secure enough. OpenSSL 3.0 doesn't allow such unsecure configuration, so failed to finish the SSL handshake.

Please use the workaround in https://github.com/yuezk/GlobalProtect-openconnect/issues/142#issuecomment-1106489685 or https://github.com/yuezk/GlobalProtect-openconnect/issues/142#issuecomment-1111887471

**Comment by yuezk** [comment]
Fixed in 1.4.2

**Comment by LauroSilveira** [comment]
Good afternoon @yuezk, thank you!
