### ISSUE TITLE
Duo authentication failing 'Unknown error'

### ISSUE THREAD

**Issue by Selebian** [yuezk/GlobalProtect-openconnect#148]
First, thanks for this which is the nicest way to connect to GP VPNs

I have been using gpclient happily to connect to VPN, but something changed around 1 week ago (presumably in organisation setup). Clicking connect takes me to the web-based log in page, but after entering credentials the second stage (my organisaion uses Duo for 2FA, so this is normally a frame just notifying that the push has been sent to my phone) instead shows only a red area with 'Unknown error' and there is no push notification to my phone.

I'm on Linux (Fedora 34) and gpclient 1.4.2. I have tried https://github.com/dlenski/gp-saml-gui which is still working (push notification comes to my phone, connects fine by passing over to openconnect). No custom parameters.

Happy to add a log from the terminal - are there things I should redact before posting on here, e.g. the long strings of characters passed in POST etc?

**Comment by yuezk** [comment]
Would you please post the error screenshot and logs of the `gpclient` command?

**Comment by stuartjarvis** [comment]
Log and screenshot attached. There is an error in the log, but this appears before the first log-in page comes up (the first log in page comes up fine as normal, it's only the second stage that shows the error - I cannot remember whether this was present before the current issues, I don't think I ran gpclient from the terminal except for the first time after first installing a few weeks ago)
[gpclientlog.txt](https://github.com/yuezk/GlobalProtect-openconnect/files/8651213/gpclientlog.txt)
![Screenshot_20220509_122925](https://user-images.githubusercontent.com/825907/167402089-018c39b0-5f54-45b3-95c4-8c92f9e0ad74.png)
(nothing happens when trying to click on the 'having trouble logging in?' link in the screenshot page - likely some javascript not supported by the html renderer used?)

**Comment by Selebian** [comment]
Thanks. Tried that but same visual error message as in previous screenshot. New log attached (looks similar, but some extra calls to snapchat.com?
[gpclientlog2.txt](https://github.com/yuezk/GlobalProtect-openconnect/files/8667835/gpclientlog2.txt)
)

**Comment by TedCassirer** [comment]
Do we have any updates on this issue? I have the same problem and I've not been able to fix it. I'm running it on Pop OS 22.04

**Comment by yuezk** [comment]
Hi guys, I'm trying to resolve this problem.
Have you ever succeeded with this client before? If yes, can you help try to reset the settings through the tray icon -> `Reset Settings` and start over to see if it could succeed?

**Comment by mhoran** [comment]
>  Have you ever succeeded with this client before? If yes, can you help try to reset the settings through the tray icon -> Reset Settings and start over to see if it could succeed?

Yes, it worked for some time, but stopped working around the time that this issue was opened. I say around because it actually worked until my previous Okta login timed out. Then when I was presented with a Duo Security dialog, it stopped working.

I work with @herder and use the same script to get on the VPN. The script uses `curl` to authenticate with Okta. It seems that something with QtWebEngine causes the "Unknown error" with Duo.

**Comment by yuezk** [comment]
Hi guys, I just refined the authentication workflow in 1.4.8. And added support for clearing the login cookies of the webview when clicking the `Reset Settings` menu, you are recommended to reset it first after upgrading. Please give it a try to see if it works. Thanks.

**Comment by jry-anchor** [comment]
I had the original problem running 1.4.1-ppa1~ubuntu20.04, then it magically started working again late last week. Today I upgraded to 1.4.8-ppa1~ubuntu20.04 and now it tries to connect automatically on startup, but hangs on Connecting....

I tried clearing ~/.cache/gpclient, didn't help, and I run i3 and don't have a tray icon.

these are the only thing related I see in syslog (previous to upgrade there are more detailed logs about login, gateway response, etc):
```
Jun 13 10:27:07 jr-sp /usr/lib/gdm3/gdm-x-session[105775]: 2022-06-13 10:27:07.965 INFO  [105775] [main@24] GlobalProtect started, version: 1.4.8
```

**Comment by yuezk** [comment]
@jry-anchor Thanks for your feedback.

>I run i3 and don't have a tray icon.

I will add the equivalent options of the tray menus to the `gpclient` command in the future release. For example, it could be `gpclient --reset`.

**Comment by Selebian** [comment]
Apologies for delay, I have been away.

I was the original reporter. This is now fixed for me in the latest update. Thank you for your efforts.
