### ISSUE TITLE
"Message did not meet security requirements"

### ISSUE THREAD

**Issue by fmresearchnovak** [yuezk/GlobalProtect-openconnect#201]
Trying to use this software to connect to the Franklin and Marshall College VPN service.  I installed your software and connected fine the first time.  But now every subsequent time I cannot connect, and instead get the error message "Message did not meet security requirements."

[gpclient_term_dump.txt](https://github.com/yuezk/GlobalProtect-openconnect/files/10252073/gpclient_term_dump.txt)
![Screenshot from 2022-12-17 10-37-14](https://user-images.githubusercontent.com/28933008/208249710-e7408bbc-3e51-4961-91f2-5ad7025edc13.png)
![Screenshot from 2022-12-17 10-37-04](https://user-images.githubusercontent.com/28933008/208249712-9696be66-5036-4de8-b81f-f748bc8fbd8c.png)
![Screenshot from 2022-12-17 10-27-02](https://user-images.githubusercontent.com/28933008/208249714-b43eee4f-2ea3-4535-80a4-1b90c953e094.png)

**Comment by praetorzero** [comment]
Does it happen if you click on the tray icon, reset settings, and login again?

**Comment by fmresearchnovak** [comment]
If I right click on the tray icon and select "Reset" then I can log in successfully!

This is a good work-around for me.  Thank you!  Please let me know what else (if anything) I can do to assist this project. :)

**Comment by arderyp** [comment]
I've got to ask... how secure is it using third party VPN services like this, in general? I'd think there is a serious potential threat vector.

@yuezk this seems like a very handy tool, has it had third party security audits? If so, are the reports available anywhere for us to review?

**Comment by yuezk** [comment]
@arderyp To be honest, there is a related issue #114

**Comment by arderyp** [comment]
I don't think so.  I think having a wholesale third-party security audit is a separate (and much more comprehensive) issue

**Comment by yuezk** [comment]
@arderyp how can I have the third-party security audits? Do you have any suggestions?

**Comment by arderyp** [comment]
I am not sure.  I know, for example, BitWarden has done them.

**Comment by arderyp** [comment]
it also sounds like @koraa was offering [here](https://github.com/yuezk/GlobalProtect-openconnect/issues/113#issuecomment-999529780)

**Comment by koraa** [comment]
> I've got to ask... how secure is it using third party VPN services like this, in general? I'd think there is a serious potential threat vector.

I would say you pretty much trust the VPN as much as you are trusting a public wifi…but then, you are using a VPN because you want some extra measure of security.

IIRC there is also some sort of probe feature that has openconnect execute some server-side code, but I would need to investigate that…

> @arderyp To be honest, there is a related issue https://github.com/yuezk/GlobalProtect-openconnect/issues/114

I am not sure that is true. The issue in here sounds more like some special security "detection" a business would do. It possibly points to this service doing some caching it should not do? Whether this is up to the standard this repository should implement…I do not know.

Are you on good terms with the operator of the VPN service? Maybe contact them and ask them about the error message…

> it also sounds like @koraa was offering [here](https://github.com/yuezk/GlobalProtect-openconnect/issues/113#issuecomment-999529780)

Thank you for pinging me directly. My offer of a review was mostly for the issues I raised, but I am happy to help you do a quick assessment here, but a full security review is something I would need significant funding for.

Is there anything you are interested specifically?

**Comment by koraa** [comment]
Oh let me also mention that [tunnelcrack](https://tunnelcrack.mathyvanhoef.com/) exists now.

**Comment by yuezk** [comment]
Closing it for now. Reopen if necessary.
