### ISSUE TITLE
Not working on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by javiertello** [yuezk/GlobalProtect-openconnect#210]
Hi,

With Ubuntu 20.04 it worked properly, but after update to 22.04 I get when I try to connect:

"TLS initialization failed"

I use Openconnect 8.1.

**Comment by javiertello** [comment]
Not working for me, same message. Also tested with Openconnect 8.20-1:

2023-02-01 09:53:46.724 INFO  [20534] [GatewayAuthenticator::doAuth@81] Perform the gateway prelogin at https://xxxxxxxxxxxx/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
2023-02-01 09:53:46.725 ERROR [20534] [GatewayAuthenticator::onPreloginFinished@92] Failed to prelogin the gateway at https://xxxxxxxxxxxxxxxxx/ssl-vpn/prelogin.esp?tmp=tmp&kerberos-support=yes&ipv6-support=yes&clientVer=4100&clientos=Linux, TLS initialization failed

**Comment by javiertello** [comment]
I have also tried with gp-saml-gui, and I get this response:

Unacceptable TLS certificate

**Comment by yuezk** [comment]
Is there a screenshot for this?

**Comment by yuezk** [comment]
Have you ever tried this?
```
sudo apt install --reinstall ca-certificates
```

**Comment by javiertello** [comment]
Reinstalling ca-certificates did not work. When I execute gp-saml-gui with --no-verify option it works!! 

More info here [https://github.com/dlenski/gp-saml-gui/issues/10]

There is a way to pass this option to gpclient?

**Comment by yuezk** [comment]
I'm afraid it doesn't have this option.

BTW, does it raise a certificate error if you open your VPN portal from your browser?

**Comment by javiertello** [comment]
I can access to the VPN portal from Firefox successfully.

**Comment by DavidPerezIngeniero** [comment]
A clean installation of KDE Neon based on Ubuntu 22.04 works flawlessly.

**Comment by vitkin** [comment]
There is a known issue with OpenSSL 3.0 since Ubuntu 22.04:
[openssl 3.0 - SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED](https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1963834)

That is also referenced in some Palo Alto Networks forum thread:
[SSL routines::unsafe legacy renegotiation disabled](https://live.paloaltonetworks.com/t5/general-topics/ssl-routines-unsafe-legacy-renegotiation-disabled/m-p/521376)

A workaround consist in creating an alternate OpenSSL configuration file, for example `/etc/ssl/globalprotect.openssl.cnf` with the following content:

```ini
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Options = UnsafeLegacyRenegotiation
```

And then modify the "GlobalProtect VPN" application shortcut and add as an environment variable the following:
`OPENSSL_CONF=/etc/ssl/globalprotect.openssl.cnf`

**Comment by yuezk** [comment]
Should no longer be a problem in 2.x, which has an option to ignore the TLS errors, Closing it for now, reopen it if not fixed.
