### ISSUE TITLE
On OpenSuse, DNS Servers are not updated by vpnc-script

### ISSUE THREAD

**Issue by Zombie-Ryushu** [yuezk/GlobalProtect-openconnect#322]
On OpenSuse Leap 15.5, DNS Servers are not set for the VPN.This seems to be due to vpnc-script. IP addressing works.

**Comment by yuezk** [comment]
The reason is that the client (2.1.0 and prior) didn't detect the vpnc-sript in OpenSuse 15.5. It has been fixed in the latest code base but has not been released yet.

Before that, there is a workaround for this, see https://github.com/yuezk/GlobalProtect-openconnect/issues/336#issuecomment-1991687576
