### ISSUE TITLE
Hip report update needed

### ISSUE THREAD

**Issue by tinkermakar** [yuezk/GlobalProtect-openconnect#353]
**Describe the bug**
The default hip report does not work for my needs, but I have a working example

**Expected behavior**
default hip report should work

**Environment:**
 - OS: Ubuntu 22.04
 - Desktop Environment: GNOME
 - Is remote SSH? No

**Additional context**

Here is my working example, which I generated over a year ago: [hip-report.zip](https://github.com/yuezk/GlobalProtect-openconnect/files/15180268/hip-report.zip)

I tried to mix and match to see what exactly needs to be change, but nothing worked, so sharing with a hope for you to figure out what exactly your hip report is missing for my needs that you can borrow from me... and let me (and my colleagues) use your app with no extra customization

**Comment by yuezk** [comment]
Will check it later.

**Comment by yuezk** [comment]
Hi @tinkermakar have you tried use your hip report as the `--csd-wrapper` parameter?

In GUI, you can configure it as:

<img width="446" alt="image" src="https://github.com/yuezk/GlobalProtect-openconnect/assets/3297602/16ce90c8-8052-485d-b2ab-a4ffc901b92a">

In CLI, you can use it with `sudo gpclient connect --csd-wrapper path/to/your/hipreport.sh <portal>`.

And you may need to modify the user agent because looks like your hip report is for Windows.

**Comment by yuezk** [comment]
Closing it for now, feel free to re-open if the problem still exists.
