### ISSUE TITLE
directory dist in gpgui-helper/dist

### ISSUE THREAD

**Issue by fzakaria** [yuezk/GlobalProtect-openconnect#386]
I followed instructions for BUILD_FE=0 but it would fail at the step listed:
https://github.com/yuezk/GlobalProtect-openconnect/blob/fb8fb2145018f569b6f2f9e4347cd00ed6b998c8/Makefile#L89

I got past it by doing `mkdir apps/gpgui-helper/dist` but this is likely a bug since I'm guessing this director doesn't need to exist.

**Comment by yuezk** [comment]
Hi @fzakaria if you run the command `make build BUILD_FE=0` to build it from the source code, ensure that the source tarball is downloaded from the [release page](https://github.com/yuezk/GlobalProtect-openconnect/releases), because the source tarball on the release page has pre-compiled the front-end script. So we can skip the front-end building with `BUILD_FE=0`.

Otherwise, you should have the Nodejs and the `pnpm` command installed on your system and run `make build` without the `BUILD_FE=0` flag.

**Comment by fzakaria** [comment]
Ah okay.  
I just did a git checkout.
