### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by pombredanne** [yuezk/GlobalProtect-openconnect#438]
Hi, thanks for this tool.
Your readme states:

> The GUI version is partially open source. Its background service is open sourced in this repo as gpservice. The GUI part is a wrapper of the background service, which is not open sourced.

Can you elaborate what you mean here? Does this mean that this tool is built from some binaries?
I would like to clearly understand what is the situation before downloading any pre-built random binaries for a VPN client. What could be going wrong with this?

**Comment by yuezk** [comment]
Hi @pombredanne, The GUI version consists of three parts:

- The backend service (gpservice), which is to connect to your VPN server, is open-sourced. The source code is https://github.com/yuezk/GlobalProtect-openconnect/tree/main/apps/gpservice
- The browser authentication part, is open-sourced. The source code is https://github.com/yuezk/GlobalProtect-openconnect/tree/main/apps/gpauth
- The GUI application, with which you interact, is not open-sourced.

The GUI application communicates with the backend service via WebSocket. You can think of the GUI application as a client of the backend service. Anyone can implement their client for the backend service because the communication data structure is open-sourced in https://github.com/yuezk/GlobalProtect-openconnect/tree/main/apps/gpapi.

Hope this clarifies your confusion.
