### ISSUE TITLE
Save credentials

### ISSUE THREAD

**Issue by kaihendry** [yuezk/GlobalProtect-openconnect#60]
Once disconnected, I need to put my username and password in again. Is there a way to automate this process please?

**Comment by gobonja** [comment]
There seems to be an issue with multiple gateways because in GPClient.conf new line is added below [General] and above 
`vpn.blabla.com_selectedGateway=vpn.blabla.com`
 line added: 
`vpn.blabla.com_gateways="[\n    {\n        \"address\": \"vpn.blabla.com.com\",\n        \"name\": \"vpn.blabla.com\"\n    }\n]\n"`

There is a workaround for this issue:

1. after successful connection remove newly created line in ~/.config/com.yuezk.qt/GPClient.conf and save file
2. set GPClient.conf readonly with: `sudo +i ~/.config/com.yuezk.qt/GPClient.conf`
3. restart Global Protect client and connect

**Comment by atharen** [comment]
For reference, there is effort being done to get this integrated. https://github.com/yuezk/GlobalProtect-openconnect/pull/109

**Comment by yuezk** [comment]
Well supported in the 2.x release, closing.
